### ISSUE TITLE
Platforms supported

### ISSUE THREAD

**Issue by alexkart** [flow-php/etl-examples#2]
Does it only support PostgreSQL?
I'm trying to connect to MariaDB or MySQL and it says those platforms are not yet supported?
What options do I have if I need to read and write to MariaDB?

**Comment by norberttech** [comment]
Hey @alexkart, reading should work out of the box but writing at this point is possible only to PostgreSQL sink. 

The limitation comes from the fact that Doctrine by default does not have any good bulk upserts support. 
In order to cover that gap, we developed [doctrine-dbal-bulk](https://github.com/flow-php/doctrine-dbal-bulk) which due to our internal use cases was developed with [PostgreSQL Dialect](https://github.com/flow-php/doctrine-dbal-bulk/blob/1.x/src/Flow/Doctrine/Bulk/Dialect/PostgreSQLDialect.php). 

[Dialect](https://github.com/flow-php/doctrine-dbal-bulk/blob/1.x/src/Flow/Doctrine/Bulk/Dialect/Dialect.php) is a pretty flexible abstraction for bulk operations so it should be relatively straightforward to add MariaDB support as it is also supported by Dbal. 

Adding support for MariaDB is on our roadmap but due to other important topics, I can't promise any deadline for it.  
You are also more than welcome to give it a try and open a PR

**Comment by alexkart** [comment]
> You are also more than welcome to give it a try and open a PR

Thanks for the reply. I'll try to make a PR. It would be helpful if you could give me some guidance or additional info on what should be implemented.

**Comment by norberttech** [comment]
I just updated [doctrine-dbal-bulk](https://github.com/flow-php/doctrine-dbal-bulk) repository readme with [Adding new Dialects](https://github.com/flow-php/doctrine-dbal-bulk#adding-new-dialects) chapter. 

I'm closing this issue, in case of any questions don't hesitate to open a new one in doctrine-dbal-bulk repo, I will do my best to guide you through the process of adding support for MariaDB dialect.
